### ISSUE TITLE
booting 

### ISSUE THREAD

**Issue by robi62** [Leo3213/HP-ProBook-450-G3-hackintosh-bigsur-11.3#12]
Hi I by luck found your github wonderful so I can boot to windows to
My hp is a 430 g3 which is almost identical The only problem i have is that I can only boot in verbose If i do a normal boot does not do anything Any ideas???
Regards
Roberto

**Comment by robi62** [comment]
I found out what it is I use fakesmc because I like to see sensors and fan rpm with hwmonitor but When I use kexts in clover other it does not boot in normal mode but yes in verbose No idea how to make it boot in normal mode with fakesmc....

**Comment by Leo3213** [comment]
I do not but good to know fake SMC works.

Also out of curiosity I'm assuming you removed virtualsmc when you replaced it with fake smc

**Comment by robi62** [comment]
Actually it dos not boot If I take virtualsmc off they are in kext folder together The only thing that I had to do is use usb kext from another guy as yours would not work for my 2 righthand sids usb
Im not complaining at least I can do dual boot with win10 with clover as Opencore it injects in windows and I cannot boot because I get api errors

**Comment by Leo3213** [comment]
Oh good to know. USB mapping only works on the exact device
