### ISSUE TITLE
hdmi sound not working

### ISSUE THREAD

**Issue by robi62** [Leo3213/HP-ProBook-450-G3-hackintosh-bigsur-11.3#13]
hi I have noticed with all GitHub for this laptop hdmi sound does not work although everyone says it does????
I get no sound option for my tv when I connect hdmi cable it still only shows internal speakers???

**Comment by robi62** [comment]
I managed to Fix it thanks to OSx latitude add this to device
framebuffer-con1-enable       1        NUMBER
framebuffer-con1-type         00080000 DATA

**Comment by Leo3213** [comment]
Hey I'll look into these thank you for all the suggestions 😇
